### ISSUE TITLE
add a license

### ISSUE THREAD

**Issue by a-detiste** [chocolate-doom/icon#1]
Hi,

can you add licensing terms for heretic-icon.svg ? GPL2+ or MIT is perfect

I would like to reuse it in Debian's game-data-packager .

:smile: 

@fabiangreffrath

**Comment by a-detiste** [comment]
My icon skills are worse than yours: https://github.com/a-detiste/game-data-packager/blob/master/data/chex.svg

**Comment by fragglet** [comment]
Looks like I forgot to include a COPYING file, but to clarify: these are all GPL.

The Heretic icon is a work in progress - I never got round to finishing it and it never went into use for Chocolate Heretic because I wasn't satisfied with it. But if you think it's good enough then by all means use it.

I'll leave this bug open so that I remember to add a COPYING file to the repository.

**Comment by fragglet** [comment]
Oh, and I planned to do similar icons for Chocolate Hexen (should be the ice cream + stylized Hexen-like 'X'), and for Chocolate Strife (less sure about this, could be ice cream + something resembling the Strife sigil; I'd like to know if @haleyjd has any thoughts). The part representing the game should be done from scratch and intentionally different from the game logo - the 'D' in the Chocolate Doom logo for example is deliberately different from the 'D' in the Doom logo.

I hadn't considered doing one for Chex Quest but I guess it would be nice to have too.

**Comment by a-detiste** [comment]
thanks :smile:  

>  The part representing the game should be done from scratch and intentionally different from the game logo

Yeah, I noticed the official Chex Quest icon, but instead I went with a generic 4x4 waffle I made myself.

**Comment by haleyjd** [comment]
Are you sure you don't want to possibly consider a more appropriate content license like CC BY-SA, Free Art License, etc. ? This came up in chat in #doomwiki since the choco logo was recently uploaded there, with questions about how we make sure we're properly distributing the "source code" for a PNG image file.

**Comment by a-detiste** [comment]
> the "source code" for a PNG image

well in the package I've been working on, the Doom Wikia logo was translated once in XPM ('the source') and is then translate back to .png on each build https://github.com/a-detiste/game-data-packager/blob/master/data/doom-common.xpm ; do you mean that or some .svg the .png is created from ?

CC BY-SA would be nice too; and the author would be aknoweledged in generated .deb packages .
https://wiki.debian.org/DFSGLicenses#Creative_Commons_Attribution_Share-Alike_.28CC-BY-SA.29_v4.0

**Comment by haleyjd** [comment]
Maybe dual licensing GPL + BY-SA? Because, even if we were to eschew the PNG versions on DoomWiki.org for SVG, which is technically source code in its own right, the MediaWiki software by its nature automatically creates PNGs for serving to end users, who can then save the derivative works and potentially reuse them.

**Comment by fragglet** [comment]
Since you mentioned Wikia, I'm obliged to politely ask you to please not
use that website; it is the old version of the Doom wiki. The Doom wiki
moved to doomwiki.org some time ago. Wikia refuses to take down wikis even
when there is consensus among admins to leave.

On 9 March 2015 at 17:10, Alexandre Detiste notifications@github.com
wrote:

> the "source code" for a PNG image
> 
> well in the package I've been working on, the Doom Wikia logo was
> translated once in XPM ('the source') and is then translate back to .png on
> each build
> https://github.com/a-detiste/game-data-packager/blob/master/data/doom-common.xpm
> ; do you mean that or some .svg the .png is created from ?
> 
> CC BY-SA would be nice too; and the author would be aknoweledged in
> generated .deb packages .
> 
> https://wiki.debian.org/DFSGLicenses#Creative_Commons_Attribution_Share-Alike_.28CC-BY-SA.29_v4.0
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chocolate-doom/icon/issues/1#issuecomment-77943327.

## 

Simon Howard
https://soulsphere.org/

**Comment by fragglet** [comment]
In principle I don't have any strong objections to dual licensing the
artwork under an additional license but I'm finding it hard to see what
real benefit there would be to doing so. There's also the fact that the ice
cream part of the logo is actually by a photographer (Chris Metcalf) whom I
convinced to allow his work to be GPL-licensed for the Chocolate Doom logo.
Any relicensing would need his permission and I'm hesitant to bug him about
it unless there's a strong case for it.

On 9 March 2015 at 17:01, James Haley notifications@github.com wrote:

> Are you sure you don't want to possibly consider a more appropriate
> content license like CC BY-SA, Free Art License, etc. ? This came up in
> chat in #doomwiki since the choco logo was recently uploaded there, with
> questions about how we make sure we're properly distributing the "source
> code" for a PNG image file.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chocolate-doom/icon/issues/1#issuecomment-77941696.

## 

Simon Howard
https://soulsphere.org/

**Comment by a-detiste** [comment]
Wikia: This XPM was translated back in 2007.

**Comment by haleyjd** [comment]
@fragglet: I wasn't aware of the history and that it would be complicated, so that's alright. If you have any input to give on the wiki usage of the image I'll let you bring it there for discussion if you want.

**Comment by fragglet** [comment]
Ah, fair enough then :)

On 9 March 2015 at 17:32, Alexandre Detiste notifications@github.com
wrote:

> Wikia: This XPM was translated back in 2007.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chocolate-doom/icon/issues/1#issuecomment-77947552.

## 

Simon Howard
https://soulsphere.org/

**Comment by fragglet** [comment]
Bug fixed. I'm going to file bugs for adding other icons.
